# CI for NVIP

name: Java CI

on: [push]

env:
  AWS_REGION: 'us-east-1'

jobs:
  build-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build API with Gradle
        run: |
          gradle test --no-daemon

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-test-api
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create Temporary Directory
        run: mkdir tmp

      - name: Create ZIP File
        run: |
          zip -r ./tmp/api.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: nvip-api
          environment_name: nvip-api-prod
          version_label: ${{ github.sha }}
          region: ${{ env.AWS_REGION }}
          deployment_package: ./tmp/api.zip
